apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: rejp5dvau-java-quarkus
  janus-idp.io/tekton: rejp5dvau-java-quarkus
  backstage.io/kubernetes-id: rejp5dvau-java-quarkus
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: rejp5dvau-java-quarkus
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
